# Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

  title: "OCI CLI VM"
  description: "Creating a environment for OCI CLI"
  schemaVersion: 1.2.0
  version: "20250521"
  locale: "en"

#################
# Variables
#################
  variableGroups:
  - title: General Configuration
    visible: true
    variables:
    - region
    - compartment_ocid
    - tenancy_ocid
    - solution_name
    - network_cidr

  - title: Security Configuration
    visible: true
    variables:
    - ssh_key_public
    - ssh_key_private

  - title: Resources Configuration
    visible: true
    variables:
    - shape
    - shape_cpu
    - shape_memory
    - shape_disk

  variables:
    region:
      title: Region
      description: The OCI region where the resources will be created.
      type: oci:identity:region:name
      required: true

    compartment_ocid:
      title: Target Compartment
      description: The ID of the Target Compartment where to create all the resources.
      type: oci:identity:compartment:id
      required: true

    tenancy_ocid:
      title: Tennant
      description: The ID of the OCI Tennat.
      type: oci:identity:tennant:id
      required: true

    solution_name:
      title: Solution Name
      description: Name of the solution without spaces.
      type: string
      default: "MyCli"
      required: true
      pattern: ^(([A-Z]{1})([A-Za-z0-9]{1,31}))$

    network_cidr:
      type: string
      title: "CIDR Block for VCN"
      description: "CIDR Block for VCN eg. [10.0 - 10.255, 172.16 - 172.31, 192.168]"
      required: true
      default: "10.0"
      visible: true
      pattern: "^((10.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))|(192.168)|(172.(1[6-9]|2[0-9]|3[01])))$"

    ssh_key_public:
      title: Public SSH Key
      description: The public ssh key for creation of the resources.
      type: oci:core:ssh:publickey
      required: true

    ssh_key_private:
      title: Private SSH Key
      description: The private ssh key for creation of the resources.
      type: file
      required: true

    shape:
      title: VM Shape
      type: enum
      enum:
        - "VM.Standard.E5.Flex"
        - "VM.Standard3.Flex"
      default: "VM.Standard.E5.Flex"
      required: true

    shape_cpu:
      title: OCPU per VM
      description: Number of OCPU per VM [1 - 2]
      type: integer
      default: 1
      required: true
      minimum: 1
      maximum: 2

    shape_memory:
      title: Memory per VM
      description: Number of Memory per VM [2 - 16]
      type: integer
      default: 4
      required: true
      minimum: 2
      maximum: 16

    shape_disk:
      title: Disk per VM
      description: Size of disk per VM [50 - 100]
      type: integer
      default: 50
      required: true
      minimum: 50
      maximum: 100
